### ISSUE TITLE
Using ms2pip from within python console or script

### ISSUE THREAD

**Issue by MKoesters** [compomics/ms2pip_c#130]
Hi all,

Thanks for the great tool!
I'd like to know if its currently possible to import ms2pip in a python script or the console, run the predictions and get the results in form of a pandas dataframe or similar?

Best,
Manuel

**Comment by MKoesters** [comment]
I guess `from ms2pip.ms2pipC import MS2PIP` was what I have been looking for

**Comment by RalfG** [comment]
Hi! Indeed, you can make an `ms2pip.ms2pipC.MS2PIP()` instance:

```python
from ms2pip.ms2pipC import MS2PIP

ms2pip_runner = MS2PIP(<options>)
ms2pip_runner.run()
```
where `<options>` are about the same as the command line options: `pep_file` can be either the path to a PEPREC file or a `pandas.DataFrame` containing the PEPREC, and `params` is a dict with the same options as the ms2pip config file. Then you can call `.run()` on the ms2pip instance. 

You can find an example in the tests:

https://github.com/compomics/ms2pip_c/blob/b7df0fccdc199f3a75b9580f14d9cd51f66d4517/tests/test_predictions.py#L11-L42

_(Documentation should be improved on this: #131)_


We do not use MS²PIP in this way very often, so do let us know if you run into any issues.

Thanks!

**Comment by MKoesters** [comment]
Perfect, thanks for the fast answer!


I'll play a bit around with that class next week, and let you know how it worked for me.
If I'm sure I understand all the parameters, I'd also be willing to contribute a docstring and a small example, if thats fine for you.

**Comment by RalfG** [comment]
Sure, thanks! Contributions are always welcome!
