### ISSUE TITLE
Installation fails with VS14 Error D8021

### ISSUE THREAD

**Issue by JB91451** [compomics/ms2pip_c#141]
Dear all,

I have some trouble installing ms2pip on my local computer. After creating and switching to a venv, I tried both, the direct installation via pip and installation of the editable version. Both fail after installing most (/ all?) dependencies and copy of the model files with the error shown below. 
Does anyone has an idea how to solve this?

Best regards,
Juergen

![MS2PIP_InstallError](https://user-images.githubusercontent.com/51822132/118644042-9c211000-b7dd-11eb-9793-132c8d169c09.PNG)

The computer runs on win7 (64bit) but the same error occurs on a win10 machine
Python: 3.8.3
VS: 14.2

**Comment by RalfG** [comment]
Hi, MS²PIP is only available on Linux and macOS. On Windows, you can run MS²PIP using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10). You can also use our webserver on [iomics.ugent.be/ms2pip](https://iomics.ugent.be/ms2pip)

**Comment by JB91451** [comment]
Hi Ralf, Thank you for the information. I will try to find a Linux computer in our institute, as we will likely use MS2PIP more often.

Best,
Juergen

**Comment by RalfG** [comment]
Hi @JB91451,

As of version 3.8.0, MS²PIP can be installed on Windows:  
https://github.com/compomics/ms2pip_c/releases/tag/v3.8.0

We alo provide new prediction models with improved accuracy and compatibility for non-tryptic peptides, such as immunopeptides.

Best,
Ralf
