### ISSUE TITLE
when  i apply the ms2pip, the error occur:   No module named 'ms2pip'

### ISSUE THREAD

**Issue by ningzaizia** [compomics/ms2pip_c#143]
Dear author:
I am apply your ms2pip to deal with my MS-data. I have installed the ms2pip in linux system. But when i use the ms2pip to predict my spectral library, there is a error: 
```
File "~/bin/ms2pip", line 1, in <module>
from ms2pip.__main__ import main
ModuleNotFoundError: No module named 'ms2pip'.
```
and my script is :
`~/bin/ms2pip -c ./config.txt ./PePrec.txt.peprec`
I don't know how to solve the problem,  I will be very appreciated if you can give me a help.

**Comment by RalfG** [comment]
Hi @ningzaizia,
Did we already correspond via email to fix your issue?

**Comment by ningzaizia** [comment]
Hi Ralf,
Ning zaizia is my GitHub account.
Yes，the problem was deal with now by email.
Thank you so much for your help!

Best regards,
ningzaizia

发件人: Ralf Gabriels ***@***.***>
发送时间: 2021年6月28日 1:18
收件人: compomics/ms2pip_c ***@***.***>
抄送: 宁小莲(Xiaolian Ning) ***@***.***>; Mention ***@***.***>
主题: Re: [compomics/ms2pip_c] when i apply the ms2pip, the error occur: No module named 'ms2pip' (#143)


外部邮件/External Mail


Hi @ningzaizia<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fningzaizia&data=04%7C01%7Cningxiaolian%40bgi.com%7C8087681baf8c4910785008d9398f8382%7C853aa2281adc4d91bb286065c1e9963d%7C0%7C1%7C637604110842788169%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=i7stHdNpkqb5mInBP60gPUkFgpH0odAvh%2B6vY8UNcbU%3D&reserved=0>,
Did we already correspond via email to fix your issue?

―
