### ISSUE TITLE
xgboost error using model 'HCD' with fasta2speclib

### ISSUE THREAD

**Issue by AXXQ** [compomics/ms2pip_c#159]
Hi,
Thanks a lot for developing a great package!
I'm trying to use fasta2speclib with an HCD model and I'm getting the following error:

![image](https://user-images.githubusercontent.com/40174953/151917230-d8a29216-e4b4-48be-9c66-a0a6980a6db9.png)

I'm running this command: fasta2speclib -o out_lib -c config.json project.fasta
This is the config file that I use:

```

{
    "output_filetype":["csv","msp", "mgf", "bibliospec", "spectronaut", "hdf"],
    "charges":[2, 3],
    "min_peplen":8,
    "max_peplen":30,
    "missed_cleavages":2,
    "modifications":[
        {"name":"Carbamidomethyl", "unimod_accession":4, "mass_shift":57.0513, "amino_acid":"C", "n_term":false, "fixed":true}
    ],
    "ms2pip_model":"HCD",
    "decoy":true,
    "add_retention_time":false,
    "elude_model_file":null,
    "rt_predictions_file":null,
    "peprec_filter":null,
    "save_peprec":false,
    "batch_size":10000,
    "num_cpu":24
}
```

When I use the CID model instead of HCD, the function runs fine.
Do you have any suggestions?

**Comment by RalfG** [comment]
Hi @AXXQ,

Thanks for using MS²PIP! It seems like something went wrong while downloading external model files. Can you try to first remove the `~/.ms2pip` directory, and then run fasta2speclib again?
It could be that the model did not download completely in a previous run. In an upcoming MS²PIP version, this issue should resolve itself, as MS²PIP will just retry to download the file. 

Let us know if this works!
Ralf

**Comment by AXXQ** [comment]
Hi Ralf,

Thank you for the quick response. It worked!
Thanks again for the great package!

Best Regards,
AXXQ
