### ISSUE TITLE
download models ahead of time

### ISSUE THREAD

**Issue by Seb-Leb** [compomics/ms2pip_c#163]
hello
my HPC platform doesn't allow connection to the internet. How do I simply download the models without running ms2pip. I can't seem to import predict_xgboost.py module because of circular import? I thought I would use the download_model function? 
thanks

**Comment by RalfG** [comment]
Hi @Seb-Leb,

You can download the models manually from our share: http://genesis.ugent.be/uvpublicdata/ms2pip/
and place them in the `~/.ms2pip` directory.

Do you have access to the home directory on your HPC platform? If not, we will have to add an option to MS²PIP to configure a custom model file. This is something I now realize we should do anyway.

**Comment by Seb-Leb** [comment]
I do have a home directory on our HPC. Ok, so I just put the models in `$HOME/.ms2pip/` ?

**Comment by RalfG** [comment]
Indeed, all the models you'll be using can be downloaded and added to `$HOME/.ms2pip/`
