### ISSUE TITLE
Unique indexes in pandas

### ISSUE THREAD

**Issue by edunivers** [compomics/ms2pip_c#175]
When the predec file with the input sequences has repeated peptides, i triggers a pandas error. Probably adding artificial unique indexes into the data frame or checking for duplicates would solve it.

raise ValueError("DataFrame index must be unique for orient='index'.")
ValueError: DataFrame index must be unique for orient='index'.

**Comment by RalfG** [comment]
Hi @edunivers,

Does your input PEPREC file have unique values for the `spec_id` column?  
Repeated `peptide` values should indeed be supported, but each value for `spec_id` has to be unique for MS²PIP.

Best,
Ralf
