### ISSUE TITLE
Precursor m/z restriction option (for spectral library purposes)?

### ISSUE THREAD

**Issue by patrick-willems** [compomics/ms2pip_c#187]
Hey,

Thanks for the great fasta2speclib tool, works really good! Perhaps it would be a good option to also have a filter on minimum and maximum peptide precursor m/z in the configuration file? In SWATH-MS you will have predefined min and maxima for your recorded m/z windows, hence for instance I would only be interested in 400-900 m/z peptide precursors. This might speed up the whole prediction and reduce spectral library size for a full proteome quite some. Not really a critical issue of course..

**Comment by RalfG** [comment]
Sounds like a good idea! We are in the process of refactoring fasta2speclib, so I can easily add it to the wish list.

**Comment by RalfG** [comment]
Closing to add this feature request to the list in #188
