### ISSUE TITLE
Possible use of ETD fragmentation

### ISSUE THREAD

**Issue by ericmalekos** [compomics/ms2pip_c#198]
Hello,
I am fairly new to working with proteomics data but would like to use MS2PIP to rescore output from MSGF+. The [original data from a PRIDE](https://proteomecentral.proteomexchange.org/cgi/GetDataset?ID=PXD008733) says it was collected on Orbitrap Fusion Lumos which [seems to use ETD fragmentation](https://www.thermofisher.com/order/catalog/product/IQLAAEGAAPFADBMBHQ). This is not a model that MS2PIP currently supports, does it make sense to run with some other model (HCD?,  etc.) or are the approaches incompatible?

Sorry for the basic question

**Comment by RalfG** [comment]
Hi Eric,

Thanks for your interest in MS²PIP! Currently, ETD is indeed not supported, and unfortunately the fragmentation is so drastically different from CID/HCD that using one of the existing models will not help at all. You could still use [MS²Rescore](https://github.com/compomics/ms2rescore) without MS²PIP, but with DeepLC for additional retention time prediction. This should already improve upon the standard Percolator rescoring.

In the future, we could add models for ETD, but this is currently not on our roadmap for MS²PIP.

Best,
Ralf
