### ISSUE TITLE
Can ms2pip predict relative precursor ion intensities?

### ISSUE THREAD

**Issue by photocyte** [compomics/ms2pip_c#199]
Hi there,

It seems clear that ms2pip can predict fragment ion intensities within an MS/MS spectra from a peptide sequence alone, but can it also predict how well the peptide would ionize from its sequence? In other words, what the intensity is of the MS1 precursor ion. If not, do you recommend any software to do this in combination with ms2pip? 

All the best,
-Tim

**Comment by RalfG** [comment]
Dear Tim,

Thanks for your question! Unfortunately, no. MS²PIP strictly predicts MS/MS spectra. There are a large number of proteotypicity predictors (such as most recently, [DeepDetect](https://pubs.acs.org/doi/full/10.1021/acs.analchem.2c03662)), although these tools usually predict a probability of finding a certain peptide. This includes both whether it will be efficiently digested by the enzyme (e.g., trypsin), and whether it is well-ionizable for mass spec. However, I am not sure if there already are predictors for MS1 intensity given a certain abundance in the sample. 

Hope this helps a bit.

Best,
Ralf

**Comment by photocyte** [comment]
Thank you! Will give DeepDetect a shot, hopeful that I can use MS2PIP later as well.
