### ISSUE TITLE
Prediction model with a different instrument

### ISSUE THREAD

**Issue by tretyacv** [compomics/ms2pip_c#204]
Hello, would you consider the TTOF5600 model applicable to TTOF6600 spectra prediction?

**Comment by JB91451** [comment]
Hi,

I am not a developer of ms2pip but a (former) user of TTof instruments. Fragmentation in both instruments is essentially the same. There are only some differences in the ion path etc. but ms2 spectra should behave the same. So I would guess that there are no issues in applying the TTof5600 model to TTof6600.

Best,
Juergen

**Comment by RalfG** [comment]
Hi @tretyacv,

I second Juergen's comment. I assume they will be extremely similar. You could also try the latest HCD model, as we have seen that Orbitrap and Sciex TOF fragmentation patterns are quite similar too (https://pubmed.ncbi.nlm.nih.gov/31028400/#&gid=article-figures&pid=figure-1-uid-0), and the latest HCD model is a bit more performant in general than our older models.

Best,
Ralf
