### ISSUE TITLE
How to convert msgf+ output to peprec?

### ISSUE THREAD

**Issue by JannikSchneider12** [compomics/ms2pip_c#208]
Hey everyone,

I have used msgf+ and now have either an mzid and/or a tsv results file. Now I wanted to convert this to a valid peprec file for ms2pip. I tried the conversion scripts but it seems like non of them is specified for this kind of files?

Thanks for your time and help

**Comment by RalfG** [comment]
Hi Jannik, 

Depending on your use case, it might be better to try out v4.0 of MS²PIP, which is currently in 'dev' releases. This version uses compomics/psm_utils to read the peptide information, and `.mzid` is one of the natively supported file formats. The only drawback currently is that not all spectral library formats have been implemented yet.

MS²PIP 4.0 can be installed with:
```
pip install ms2pip --pre
```

Let us know if this solves your issue.

Best,
Ralf
