### ISSUE TITLE
custom FASTA

### ISSUE THREAD

**Issue by Kokoushin** [compomics/ms2pip_c#212]
Hi,

I attempted to process a custom FASTA file using the online "From protein FASTA file". 

The processing of FASTA_A was successful, but for FASTA_B, it displayed "Something went wrong.
[FASTA_A.txt](https://github.com/compomics/ms2pip/files/14221285/FASTA_A.txt)
[FASTA_B.txt](https://github.com/compomics/ms2pip/files/14221287/FASTA_B.txt)

**Comment by Kokoushin** [comment]
Since GitHub does not support uploading FASTA files, I converted them to TXT format.

**Comment by RalfG** [comment]
Hi @Kokoushin,

Thanks for using MS²PIP! I noticed there is a `*` in FASTA_B. This most likely represents 'any' amino acid, but that is not supported by MS²PIP.

Best,
Ralf

**Comment by RalfG** [comment]
After removing the protein with the `*`, this is the result: https://iomics.ugent.be/ms2pip/result/83fe9c97-e7ab-458d-b014-e2f1a630aeb1
