### ISSUE TITLE
Define cache dir for xgboost models

### ISSUE THREAD

**Issue by jonasscheid** [compomics/ms2pip_c#218]
This feature request came up in https://github.com/nf-core/mhcquant/issues/317

Currently, the xgboost models are always downloaded to `$HOME/.ms2pip`. In some cases that could lead to permission issues, but the major advantage here would be in containerized settings, where containers are built from their image every time leading to downloading the xgboost models over and over again.

Would be great to have an option to specify a cache directory, where models can be reused.

**Comment by RalfG** [comment]
Hi Jonas,

In MS²PIP 4.0, a `model-dir` option is available (e.g. for [`correlate`](https://ms2pip.readthedocs.io/en/latest/api/ms2pip/#ms2pip.correlate)), exactly for this purpose. Can you check if that does what you had in mind?

Best,
Ralf

**Comment by jonasscheid** [comment]
Great! That is exactly what I was looking for 🙌🏼
And it worked! Thanks for the pointer Ralf 😎
