### ISSUE TITLE
pre-digest fasta for library generation

### ISSUE THREAD

**Issue by gukongxin** [compomics/ms2pip_c#221]
Hi,

Thank you for developing MS2PIP. 
[diann_001.txt](https://github.com/compomics/ms2pip/files/15249813/diann_001.txt)

I have a pre-digested (trypsin) FASTA file and I want to create an in silico library using MS2PIP.
I tried using the MS2PIP online server, but it failed. 
Here is my FASTA file.

Best regards,
Ko

**Comment by RalfG** [comment]
Hi @gukongxin,

Thanks for using MS²PIP!

Normally MS²PIP FASTA input is meant to contain full protein sequences that still have to be digested, not pre-digested peptides. On the online server this is entirely unsupported. You could either run fasta2speclib locally using the command line interface, or provide an undigested protein FASTA on the webserver. 

To run MS²PIP locally with the peptide FASTA, you can set the `cleavage_rule` to `-`, `min_length` to `0`, and `max_length` to a very high value, e.g., `1000`. I did this for the file you uploaded with the default search space parameters (Orbitrap HCD, variable M oxidation, fixed C carbamidomethylation, charges 2 and 3...). The resulting MSP file can be downloaded here: https://filesender.belnet.be/?s=download&token=8b37fcda-0819-481e-929c-4c30641f8c58

I recommend using the dev versions of MS²PIP 4.0 (which is to be released as stable very soon). It can be installed with pip with the following command:

```
pip install ms2pip --pre
```

Then run ms2pip as follows:

```
ms2pip predict-library --processes 12 -c <path/to/config.json> <path/to/peptides.fasta>
```

where `<path/to/config.json>` and `<path/to/peptides.fasta>` are replaced with the actual file paths. All CLI options can be found [here](https://ms2pip.readthedocs.io/en/latest/cli/cli/#ms2pip-predict-library) and more info on the search space configuration can be found [here](https://ms2pip.readthedocs.io/en/latest/api/ms2pip.search-space/).


Let me know if you need further help.

Best,
Ralf

**Comment by gukongxin** [comment]
Thank you for your prompt and detailed reply.

Best regards,
Ko
