### ISSUE TITLE
predicted library for DIA-NN (question)

### ISSUE THREAD

**Issue by Li5459000** [compomics/ms2pip_c#222]
Hi Ralf,

I'm currently using MS2PIP to predict a spectral library for DIA-NN analysis. I obtained a '.msp' file and loaded it into the 'spectral library' of the DIA-NN GUI. But DIA-NN does not support this file type.

I'm sorry, I've just started working in the field of proteomics.

Best Regards,
Li

**Comment by RalfG** [comment]
Hi Li,

Apologies for the delayed response. Do you still have the error that DIA-NN produced when importing the MSP library? We have tested MSP files specifically for DIA-NN, but perhaps something changed since our previous test.

Thanks!
Ralf
