### ISSUE TITLE
Error while install ms2pip v4.0.0

### ISSUE THREAD

**Issue by Yanidzilla** [compomics/ms2pip_c#224]
![Screenshot 2024-07-10 122401](https://github.com/compomics/ms2pip/assets/147511279/1fb45643-afdd-4f2e-8551-ceb4d40499a7)

Dear developpers,

I git clone the latest compomics, and git checkout v4.0.0. Then, I tried to install it in ms2pip folder via: pip install .
It gives me the following error message. I use python3.8.

Best regards.

**Comment by RalfG** [comment]
Hi @ZhaoYaniBruker,

For simple usage, it is easier to install ms2pip from PyPI with

```sh
pip install ms2pip
```

If you do wish to install MS²PIP from source (for instance for development) as you did, ensure that [Git Large File Storage (LFS)](https://git-lfs.com/) is installed on your system. Some files (older models in C) have been uploaded to GitHub with LFS. 

After installing Git LFS, fetch and checkout the LFS files in the repo:

```sh
git lfs fetch
git lfs checkout
```

To validate that the LFS checkout went correctly, you can check that the top of the file `ms2pip/_models_c/HCD-2019/model_20190107_HCD_train_B.c` looks like this:

```c
#include "../HCD-2019.h"

float score_HCD_B(unsigned int* v){
float s = 0.;
        if (v[27]<6){
...
```

If it looks like this:
```txt
version https://git-lfs.github.com/spec/v1
oid sha256:d0ab6fdc7c3b2324228912757d1c55bd56fdebbe066a0b5fc0305f0c7bbb9969
size 8726156
```
the repo was not cloned with LFS and MS²PIP won't compile.


Best,
Ralf
