### ISSUE TITLE
Link is broken for downloading model

### ISSUE THREAD

**Issue by shubham1637** [compomics/ms2pip_c#229]
Hi, 
    I am trying to download MS2pip model 'Immuno-HCD' for mhcquant. However, the [link]("http://genesis.ugent.be/uvpublicdata/ms2pip/") is broken.

https://github.com/compomics/ms2pip/blob/d2a42819e24546db44f2d91eb9b7f47ed702a43e/ms2pip/_utils/xgb_models.py#L92

Could you update the link?

**Comment by RalfG** [comment]
Hi @shubham1637,

Thanks for using MS²PIP! 

Both links seem to be working for me:
- http://genesis.ugent.be/uvpublicdata/ms2pip/model_20210316_Immuno_HCD_B.xgboost
- http://genesis.ugent.be/uvpublicdata/ms2pip/model_20210316_Immuno_HCD_Y.xgboost

If it still does not work as part of MS²PIP, you could download the models manually from Zenodo at https://zenodo.org/records/13270668 and place them in a directory `.ms2pip` in your home folder. On the different platforms, this should be:

- Windows: `%userprofile%/.ms2pip`
- macOS and Linux: `~/.ms2pip`

Let us know if this helped.

Best,
Ralf

**Comment by shubham1637** [comment]
Thanks a lot. I was able to download the models.
