### ISSUE TITLE
online prediction failed 

### ISSUE THREAD

**Issue by wangss3** [compomics/ms2pip_c#235]
Hi,

I tried using the online prediction tool (from a protein FASTA file), but it failed.

Today, I tried again, but after clicking 'Upload your FASTA file,' nothing happened.
FASTA files cannot be unloaded.

I have not used Python before, so I can only rely on the online prediction tool. 

Thank you for your help in advance.

**Comment by RalfG** [comment]
Hi @wangss3,

Thanks for letting us know! An upstream change broke some things on the website. The issues are now fixed. Can you try again?

Best,
Ralf

**Comment by wangss3** [comment]
Now it works
