### ISSUE TITLE
ms2pip_tools folder not installed

### ISSUE THREAD

**Issue by tuxmaster5000** [compomics/ms2pip_c#30]
When install the module via 
/usr/bin/python3.6 setup.py install -O1 --skip-build --root /builddir/build/BUILDROOT/python-ms2pipC-1.1.0-1.el7.x86_64
the ms2pip_tools module will not installed to the system python module folder.
Only the the cython part are installed.

**Comment by RalfG** [comment]
Hi @tuxmaster5000, 

Right now, installing MS²PIP as a package is not supported. It is something we are planning in the near future, though. The `setup.py` file is only used to compile the Cython modules and is called when `compile.sh` is ran. 
You can, however, also use the precompiled Cython files (that are posted on the [releases](https://github.com/compomics/ms2pip_c/releases/latest) page), as compiling can take a while with the latest models. Just unzip the files and put them in the `cython_modules` folder.
