### ISSUE TITLE
Use upload-artifact@v2, when released. Now using v2-preview

### ISSUE THREAD

**Issue by RalfG** [compomics/ms2pip_c#54]
`actions/upload-artifact` does not support wildcards, we'll need to find a workaround.

For example, see [v3.6.0 build](https://github.com/compomics/ms2pip_c/runs/546095906?check_suite_focus=true#step:11:7)

**Comment by paretje** [comment]
This will be available with `v2`, now available with `v2-preview`: https://github.com/actions/upload-artifact/issues/11#issuecomment-598812156
